### ISSUE TITLE
showLogs() does not run if it does not find the deployment

### ISSUE THREAD

**Issue by alvarosantamariagomez** [rstudio/rsconnect#989] opened 2023-09-01 08:20 UTC
After the update to 1.0.2 I cannot run `rsconnect::showLogs()` on a different machine that the one I use to develop and deploy.
showLogs() says it doesn't find any deployment.
This was not a problem before the last version change. Before the change, only the account (token) and the app details was enough to run showLogs().

A patch to this problem is to copy the app folder from the machine I use to deploy into the machine I use to run showLogs().
It's not a very clean solution, but at least showLogs() now finds the deployment and works again.

It would be nice if showLogs() could run anywhere independently of the app/deployment folder, as it was the case before.

Thanks, bye.

**Comment by aronatkins** [comment] 2023-09-01 13:43
Likely the same cause as https://github.com/rstudio/rsconnect/issues/985

**Comment by aronatkins** [comment] 2023-09-01 13:44
@hadley it sounds as if a number of folks were using some of the shinyapps.io helpers to inspect and monitor their applications without deployment records on-disk in a `rsconnect` directory.

**Comment by hadley** [comment] 2023-09-01 19:13
Interesting. How is it supposed to figure out what app they're interested in?

**Comment by aronatkins** [comment] 2023-09-01 19:43
We used `deploymentTarget`, which performed a search.
https://github.com/rstudio/rsconnect/blob/9ce427edf03b6d243a4074264dbc950242b0a295/R/applications.R#L211
https://github.com/rstudio/rsconnect/blob/9ce427edf03b6d243a4074264dbc950242b0a295/R/deployApp.R#L611-L612

**Comment by hadley** [comment] 2023-09-01 20:23
So that ended up using the directory name?

**Comment by aronatkins** [comment] 2023-09-01 20:32
@alvarosantamariagomez - What was your working directory you used when calling `showLogs()`? Did the name of that directory correspond to your application name, or did you provide an `appName` argument to `showLogs()`? How many different applications do you have deployed to shinyapps.io? We are trying to understand if there was something about your installation that let you locate the target application and show its logs.

**Comment by aronatkins** [comment] 2023-09-01 20:34
@hadley - https://github.com/rstudio/rsconnect/issues/980 and https://community.rstudio.com/t/shinyapps-io-deploy-error-409-application-exists-with-name/170488/7 also speak of similar problems. There was a separate problem with `showProperties()` (resolved by #984), but we're definitely missing something about how these apps were being discovered.

**Comment by alvarosantamariagomez** [comment] 2023-09-01 22:57
I have several apps deployed, but I check the logs of only one app.
None of the apps was deployed from the machine I use to check the logs.
The full command I was using in any directory of this machine was
`rsconnect::showLogs(appName="one app", streaming=F, entries=1500)`
Before being able to do that, I set my shinyapps.io account information with the token.
I assume `rsconnect` was using that information to locate the remote deployment of the app and get the log.

It could be useful to have that possibility back in the latest version, though simply copying the app folder (from the other machine where I develop & deploy) also solved my problem.
The command I have to use with `rsconnect` version 1.0.2 is
`rsconnect::showLogs(appPath="path/to/the/copied/app/folder", streaming=F, entries=1500)`

hope that helps

**Comment by aronatkins** [comment] 2023-09-05 20:42
Thanks for all that context, @alvarosantamariagomez.

**Comment by aronatkins** [comment] 2023-09-05 20:42
This issue also corresponds to customer ticket 94407.

**Comment by jacpete** [comment] 2023-09-21 16:02
I was working with a customer on a shinyapps.io ticket and ran into this issue. 
I can confirm that many shinyapps.io customers use this feature to pull logs for all their applications programmatically on a schedule because logs turn over every 1500 lines on the platform.

I found that if we just had the option to use the `appName`, `server` and `account` inputs to `showLogs()` directly, the problem could be bypassed. This removes the check that reconnect:::findDeployment was doing by verifying information in the deployment logs in the `rsconnect` directory on-disk.

My modified function I sent to a customer to get them up and running with their scripts included a new `verifyDeployment` boolean parameter and only requires modifying lines around:
```r
deployment <- findDeployment(appPath = appPath, appName = appName, 
                             server = server, account = account)
```

```r
showLogs <- function(appFile = NULL, appName = NULL, 
                     account = NULL, server = NULL, 
                     entries = 50, streaming = FALSE, 
                     verifyDeployment = TRUE) {
  
  if (verifyDeployment) {
    deployment <- findDeployment(appPath = appPath, appName = appName, 
                                 server = server, account = account)
  } else {
    if (is.null(appName) | is.null(account) | is.null(server)) {
      stop('`appName`, `account`, and `server` must be specified if `verifyDeployment` is `FALSE`.')
    }
    
    deployment <- list(
      'account' = account,
      'server' = server,
      'name' = appName)
  }
  accountDetails <- rsconnect::accountInfo(deployment$account, deployment$server)
  client <- rsconnect:::clientForAccount(accountDetails)
  application <- rsconnect:::getAppByName(client, accountDetails, deployment$name)
  if (is.null(application)) 
    stop("No application found. Specify the application's directory, name, ", 
         "and/or associated account.")
  if (streaming) {
    skip <- 0
    repeat {
      tryCatch({
        rsconnect:::streamApplicationLogs(accountDetails, application$id, 
                                          entries, skip)
        entries <- 1
        skip <- 1
      }, error = function(e) {
        if (!identical(e$message, "transfer closed with outstanding read data remaining")) {
          stop(e)
        }
      })
    }
  }
  else {
    logs <- client$getLogs(application$id, entries)
    cat(logs)
  }
}
```

This was just to get them going but it does provide the workaround these folks are looking for to manage their servers. I have recommended a format similar to the one below for several customers and an example of how they are using this function in practice.

```r
setwd('~')
appNames <- rsconnect::applications(account ='testaccountjacpete', server = 'shinyapps.io')[['name']][1:5]
file_loc <- '~/Downloads'

for (appName in appNames) {
  outputFile <- paste0(appName, "-logs_",format(Sys.time(), "%Y-%m-%d_%H-%M"), ".txt", sep = "")
  capture.output(
    {
      showLogs(appName = appName, account ='testaccountjacpete', server = 'shinyapps.io', 
               entries = 1500, verifyDeployment = FALSE)
    },
    file = file.path(file_loc, outputFile)
  )
}
```

**Closed** 2023-10-11 14:56 UTC

**Comment by aronatkins** [comment] 2023-10-11 14:59
@alvarosantamariagomez - Could you test the development version of rsconnect to see if your problem has been resolved?

```r
remotes::install_github("rstudio/rsconnect")
```

**Comment by alvarosantamariagomez** [comment] 2023-10-24 20:27
@aronatkins problem solved in showLogs() without the need of having the deployed app folder, thanks
