### ISSUE TITLE
Failed to deploy shiny app using rsconnect: Error: Unhandled Exception

### ISSUE THREAD

**Issue by mgzjys** [rstudio/rsconnect#425] opened 2020-05-06 11:03 UTC
The full error log listed as below:

```
DONE  
Uploading bundle for application: 2251357...Warning in FUN(X[[i]], ...) :  
Unable to find repository URL for package foreign
DONE
Deploying bundle: 3110420 for application: 2251357 ...
Waiting for task: 726900984
building: Processing bundle: 3110420
building: Parsing manifest
################################ Begin Task Log ################################ 
################################# End Task Log ################################# 
Error: Unhandled Exception: Child Task 726900985 failed: Error parsing manifest: Unable to determine package source for Bioconductor package oompaBase: Repository must be specified
```

I have basiclly tried everthing on the internet,  but it still didn't work.

I have added the "BiocManager" and "options(repos = BiocManager::repositories())" based on one of @kevinushey 's answer and still didn't get any luck. Below is the code:
```
library(BiocManager)  
library(rsconnect)
options(repos = BiocManager::repositories())
deployApp()
```
Anyone have any clue about this. 

Thanks!

**Comment by mgzjys** [comment] 2020-05-06 11:07
One thing very strange is the error message said:
`
Error parsing manifest: Unable to determine package source for Bioconductor package oompaBase: Repository must be specified
`
However, I was installed this package from CRAN.

**Comment by kevinushey** [comment] 2020-05-06 16:36
The problem is that `oompaBase` declares itself as a Bioconductor package -- it contains the field:

```
biocViews: Infrastructure
```

in its `DESCRIPTION` file.

**Comment by mgzjys** [comment] 2020-05-06 18:03
> The problem is that `oompaBase` declares itself as a Bioconductor package -- it contains the field:
> 
> ```
> biocViews: Infrastructure
> ```
> 
> in its `DESCRIPTION` file.

Thank you for your reply Kevin! So is there anything I can do oto detour this error?

**Comment by kevinushey** [comment] 2020-05-06 18:24
I believe you could modify the installed copy of `oompaBase` to remove that line; e.g.

```
file.edit(system.file("DESCRIPTION", package = "oompaBase"))
```

Remove the associated line, save, and attempt to deploy.

**Comment by mgzjys** [comment] 2020-05-06 18:52
> I believe you could modify the installed copy of `oompaBase` to remove that line; e.g.
> 
> ```
> file.edit(system.file("DESCRIPTION", package = "oompaBase"))
> ```
> 
> Remove the associated line, save, and attempt to deploy.

This worked now. You are great, Kevin! However, I am geting another error message for building prismatic package. Any clues about this error. I am using shinyapps.io to deploy my app.
```
Error: Unhandled Exception: Child Task 727122197 failed: Error building image: Error building prismatic (0.2.0). Build exited with non-zero status: 1
```

**Comment by kevinushey** [comment] 2020-05-06 18:55
That I don't have a great idea for -- you may want to ask on the RStudio community forums.

https://community.rstudio.com/c/shiny/shinyappsio/24

**Comment by mgzjys** [comment] 2020-05-06 18:56
Got it. Thank you Kevin. You are very helpful!

**Comment by mgzjys** [comment] 2020-05-07 15:10
> That I don't have a great idea for -- you may want to ask on the RStudio community forums.
> 
> https://community.rstudio.com/c/shiny/shinyappsio/24

Hello Kevin, I have managed to solve the problem by split my `app.R` into `server.R` and `ui.R`. 

My app was successfully deployed however still pops out some error:
<pre>
2020-05-07T14:39:25.349739+00:00 shinyapps[2260123]: Server version: 1.8.2-10
2020-05-07T14:39:25.349762+00:00 shinyapps[2260123]: LANG: en_US.UTF-8
2020-05-07T14:39:25.349763+00:00 shinyapps[2260123]: R version: 3.6.1
2020-05-07T14:39:25.349764+00:00 shinyapps[2260123]: shiny version: 1.4.0.2
2020-05-07T14:39:25.349764+00:00 shinyapps[2260123]: httpuv version: 1.5.2
2020-05-07T14:39:25.349764+00:00 shinyapps[2260123]: rmarkdown version: (none)
2020-05-07T14:39:25.349774+00:00 shinyapps[2260123]: knitr version: 1.28
2020-05-07T14:39:25.349775+00:00 shinyapps[2260123]: jsonlite version: 1.6.1
2020-05-07T14:39:25.349782+00:00 shinyapps[2260123]: RJSONIO version: (none)
2020-05-07T14:39:25.349797+00:00 shinyapps[2260123]: htmltools version: 0.4.0
2020-05-07T14:39:25.349961+00:00 shinyapps[2260123]: Using pandoc: /opt/connect/ext/pandoc2
2020-05-07T14:39:25.499320+00:00 shinyapps[2260123]: Using jsonlite for JSON processing
2020-05-07T14:39:25.508942+00:00 shinyapps[2260123]: 
2020-05-07T14:39:25.508943+00:00 shinyapps[2260123]: Starting R with process ID: '25'
2020-05-07T14:39:25.547159+00:00 shinyapps[2260123]: 
2020-05-07T14:39:25.547161+00:00 shinyapps[2260123]: Listening on http://127.0.0.1:46530
<b>2020-05-07T14:39:28.604656+00:00 shinyapps[2260123]: Warning: Error in leafglOutput: could not find function "leafglOutput"  </b>
2020-05-07T14:39:28.647417+00:00 shinyapps[2260123]:   67: dots_list
2020-05-07T14:39:28.647419+00:00 shinyapps[2260123]:   66: div
2020-05-07T14:39:28.647420+00:00 shinyapps[2260123]:   61: fluidPage
<b>2020-05-07T14:39:47.583609+00:00 shinyapps[2260123]: Warning: Error in leafglOutput: could not find function "leafglOutput"  </b>
2020-05-07T14:39:47.585509+00:00 shinyapps[2260123]:   67: dots_list
2020-05-07T14:39:47.585511+00:00 shinyapps[2260123]:   66: div
2020-05-07T14:39:47.585511+00:00 shinyapps[2260123]:   61: fluidPage
</pre>
This `leafglOutput`function came from `leafgl` which I belive have built successfully. But the shinyapps still cannot find this function. I know I am kind of asking too many questions for you but just wondering if you happened to have any clue about this. 

Many thanks!

Below is the log from shinyapps.io:
<pre>
DONE
Deploying bundle: 3116426 for application: 2260123 ...
Waiting for task: 727595926
  building: Parsing manifest
  building: Building image: 3477703
  building: Installing system dependencies
  building: Fetching packages
  building: Building package: prismatic
  building: Building package: palr
  building: Building package: sf
  building: Building package: raster
  building: Building package: satellite
  building: Building package: rpostgis
  building: Building package: oompaBase
  building: Building package: paletteer
  building: Building package: mockery
  building: Building package: colourvalues
  building: Building package: spatialwidget
  building: Building package: mapdeck
  <b>building: Building package: leafgl</b>
  building: Building package: git2r
  building: Installing packages
  building: Installing files
  building: Pushing image: 3477703
  deploying: Starting instances
  rollforward: Activating new instances
  success: Stopping old instances
Application successfully deployed
</pre>

**Comment by mgzjys** [comment] 2020-05-07 15:14
The `leafgl` package is **NOT** from CRAN, I installed it from [leafgl's Github](https://github.com/r-spatial/leafgl) using devtools. Maybe something wrong with this package? just wondering

**Comment by jmcphers** [comment] 2020-05-11 20:45
We've ruled out a bug in rsconnect here so I'm closing this issue; hopefully someone on the community forum can help you with the errors you're seeing in leafgl!

**Closed by jmcphers** 2020-05-11 20:45 UTC
