### ISSUE TITLE
applications() method call errors when nothing published yet

### ISSUE THREAD

**Issue by carlsonp** [rstudio/rsconnect#417] opened 2020-03-26 18:57 UTC
Version: `0.8.16` via CRAN

When I try to get the applications that I have published up to a Connect server and I have nothing published, I can consistently get an error message.

```
Error in `$<-.data.frame`(`*tmp*`, "config_url", value = "https://domain.../connect/#/apps/") :
replacement has 1 row, data has 0
```

Pseudo-code
```
rsconnect::addConnectServer()
rsconnect::connectApiUser()
rsconnect::applications()
```

I would expect an empty dataframe if nothing has been published.

After I manually publish something via RStudio Desktop, the call works and I get a dataframe with expected values back.

My work-around for the moment is to directly call the `__api__/aplications/?query=account_id:4` endpoint which can filter by account.

**Comment by kevinushey** [comment] 2020-05-21 16:37
Looks like a duplicate of https://github.com/rstudio/rsconnect/issues/395.

**Closed** 2021-01-29 17:54 UTC
Labels: bug
