### ISSUE TITLE
Broken deployment on Windows

### ISSUE THREAD

**Issue by cortexR** [rstudio/rsconnect#656] opened 2023-01-25 21:49 UTC
Three user have problems deplying app via rsconnect,  where deployment just freezes at "Starting to perform packrat snapshot" without any further clues to why publication process does not proceed.

See report from three users here:

https://community.rstudio.com/t/cant-deploy-app-on-shinyapps-when-package-has-special-characters-accent-on-column-names-or-variables-without-backticks/122432 

Happens on Windows. One user solved it by changing to Linux.
Common denominator seems however to be that all users use "Norwegian (Bokmål)", which uses speciel characters. Can that give a clue to what the problem is and how to solve it?

Seems like a rsconnect problem as it freezes, but rsconnect code says it should throw back som error message that it does not?

**Comment by hadley** [comment] 2023-02-21 22:01
Closing as duplicate of #233

**Closed by hadley** 2023-02-21 22:01 UTC
Labels: bug, encoding :earth_asia:, deploy :bouncing_ball_person:

**Comment by cortexR** [comment] 2023-02-21 22:24
Guess you sorted it out. 

But for any future reference, I should note that the link I gave above is wrong. This is the correct link, where the problem is described: 

https://community.rstudio.com/t/deploying-shiny-app-to-shinyapps-io-stops-at-starting-to-perform-package-snapshot/145558
