### ISSUE TITLE
support using renv for generating deployment bundles

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rsconnect#471] opened 2020-12-14 18:02 UTC
We should allow users to opt-in to using `renv` when generating deployment bundles to be used in publishing scenarios.

To ease the transition, we would first implement what is necessary in `renv` to generate a compatible Packrat lockfile, so that the existing publication workflows continue to "just work". This would allow users to reap the benefits of using `renv` for deployments, even with Packrat running in the backend.

Eventually, in the future, the backend could also support deployments using an `renv` lockfile, but that's considerably more work.

**Comment by jmcphers** [comment] 2021-02-25 00:35
See also https://github.com/rstudio/rsconnect/issues/404.

**Comment by hadley** [comment] 2023-02-23 21:16
Closing as duplicate of #404.

**Closed by hadley** 2023-02-23 21:16 UTC
Labels: dependencies :rat:, feature
