### ISSUE TITLE
Add support for deploying server-rendered static outputs to Posit Cloud

### ISSUE THREAD

**Issue by mslynch** [rstudio/rsconnect#836] opened 2023-05-05 18:36 UTC
This is an upcoming feature in Cloud that rsconnect should support.

**Comment by hadley** [comment] 2023-05-08 12:12
Duplicate of #824?

**Comment by m--** [comment] 2023-05-09 16:51
re-opening, this work still needs to be done (updated the title).

**Closed** 2023-05-30 21:35 UTC
Labels: feature, cloud :cloud_with_lightning:
