### ISSUE TITLE
Shiny app deployment: `Error: unable to satisfy package` with GitHub package

### ISSUE THREAD

**Issue by rempsyc** [rstudio/rsconnect#1121] opened 2024-12-09 22:13 UTC
I am trying to publish a shiny app using some packages that are only available on GitHub, but I am encountering the following error:

```r
Error: Unhandled Exception: child_task=1487318498 child_task_status=failed: Error building image: Error fetching 
rsconnect (1.3.3.9000) source. <GitHubPackage user='rstudio' repo='rsconnect' private=False> unable to satisfy 
package: rsconnect (1.3.3.9000)
Execution halted
```

This is the content of my file called `app.Rmd`:

````r
---
runtime: shiny
---

```{r}
library(rsconnect)
```
````

Installing `rsconnect` with `install.packages("rsconnect")` works:

``` console
── Preparing for deployment ────────────────────────────────────────────────────
✔ Re-deploying "test" using "server: shinyapps.io / username: rempsyc"
ℹ Looking up application with id "13562728"...
✔ Found application <https://rempsyc.shinyapps.io/test/>
ℹ Bundling 1 file: 'app.Rmd'
ℹ Capturing R dependencies
✔ Found 46 dependencies
✔ Created 27,859b bundle
ℹ Uploading bundle...
✔ Uploaded bundle with id 9490991
── Deploying to server ─────────────────────────────────────────────────────────
Waiting for task: 1487314909
  building: Building image: 11653465
  building: Fetching packages
  building: Installing packages
  building: Installing files
  building: Pushing image: 11653465
  deploying: Starting instances
  rollforward: Activating new instances
  success: Stopping old instances
── Deployment complete ─────────────────────────────────────────────────────────
✔ Successfully deployed to <https://rempsyc.shinyapps.io/test/>
Deployment completed: https://rempsyc.shinyapps.io/test/
```

But installing `rsconnect` with `remotes::install_github("rstudio/rsconnect")` leads to the error:
``` console
── Preparing for deployment ────────────────────────────────────────────────────
✔ Re-deploying "test" using "server: shinyapps.io / username: rempsyc"
ℹ Looking up application with id "13562728"...
✔ Found application <https://rempsyc.shinyapps.io/test/>
ℹ Bundling 1 file: 'app.Rmd'
ℹ Capturing R dependencies
✔ Found 46 dependencies
✔ Created 28,008b bundle
ℹ Uploading bundle...
✔ Uploaded bundle with id 9491010
── Deploying to server ─────────────────────────────────────────────────────────
Waiting for task: 1487318497
  building: Building image: 11653523
  building: Building package: rsconnect
## Begin Task Log ##############################################################
## End Task Log ################################################################
Error: Unhandled Exception: child_task=1487318498 child_task_status=failed: Error building image: Error fetching 
rsconnect (1.3.3.9000) source. <GitHubPackage user='rstudio' repo='rsconnect' private=False> unable to satisfy 
package: rsconnect (1.3.3.9000)
Execution halted
```

Related issue posted on Posit Forum: https://forum.posit.co/t/shiny-app-deployment-error-unable-to-satisfy-package-with-github-package/195373. The former issue I opened (and then closed) here was when investigating for this issue (#1119). I have failed to find working solutions on the Posit Forum and on Stackoverflow. I am encountering the same issue on a different computer.

---

``` r
R.version$version.string
#> [1] "R version 4.3.0 (2023-04-21 ucrt)"
packageVersion("rsconnect")
#> [1] '1.3.3.9000'
packageVersion("remotes")
#> [1] '2.5.0'
packageVersion("devtools")
#> [1] '2.4.5'
```

<sup>Created on 2024-12-09 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

``` r
rsconnect::appDependencies()
       Package    Version Source               Repository
1          PKI     0.1-14   CRAN https://cran.rstudio.com
2           R6      2.5.1   CRAN https://cran.rstudio.com
3         Rcpp   1.0.13-1   CRAN https://cran.rstudio.com
4      askpass      1.2.1   CRAN https://cran.rstudio.com
5    base64enc      0.1-3   CRAN https://cran.rstudio.com
6        bslib      0.8.0   CRAN https://cran.rstudio.com
7       cachem      1.1.0   CRAN https://cran.rstudio.com
8          cli      3.6.3   CRAN https://cran.rstudio.com
9   commonmark      1.9.2   CRAN https://cran.rstudio.com
10      crayon      1.5.3   CRAN https://cran.rstudio.com
11        curl      6.0.1   CRAN https://cran.rstudio.com
12      digest     0.6.37   CRAN https://cran.rstudio.com
13    evaluate      1.0.1   CRAN https://cran.rstudio.com
14     fastmap      1.2.0   CRAN https://cran.rstudio.com
15 fontawesome      0.5.3   CRAN https://cran.rstudio.com
16          fs      1.6.5   CRAN https://cran.rstudio.com
17        glue      1.8.0   CRAN https://cran.rstudio.com
18       highr       0.11   CRAN https://cran.rstudio.com
19   htmltools    0.5.8.1   CRAN https://cran.rstudio.com
20      httpuv     1.6.15   CRAN https://cran.rstudio.com
21   jquerylib      0.1.4   CRAN https://cran.rstudio.com
22    jsonlite      1.8.9   CRAN https://cran.rstudio.com
23       knitr       1.49   CRAN https://cran.rstudio.com
24       later      1.4.1   CRAN https://cran.rstudio.com
25   lifecycle      1.0.4   CRAN https://cran.rstudio.com
26    magrittr      2.0.3   CRAN https://cran.rstudio.com
27     memoise      2.0.1   CRAN https://cran.rstudio.com
28        mime       0.12   CRAN https://cran.rstudio.com
29     openssl      2.2.2   CRAN https://cran.rstudio.com
30     packrat      0.9.2   CRAN https://cran.rstudio.com
31    promises      1.3.2   CRAN https://cran.rstudio.com
32    rappdirs      0.3.3   CRAN https://cran.rstudio.com
33        renv     1.0.11   CRAN https://cran.rstudio.com
34       rlang      1.1.4   CRAN https://cran.rstudio.com
35   rmarkdown       2.29   CRAN https://cran.rstudio.com
36   rsconnect 1.3.3.9000 github                     <NA>
37  rstudioapi     0.17.1   CRAN https://cran.rstudio.com
38        sass      0.4.9   CRAN https://cran.rstudio.com
39       shiny      1.9.1   CRAN https://cran.rstudio.com
40 sourcetools    0.1.7-1   CRAN https://cran.rstudio.com
41         sys      3.4.3   CRAN https://cran.rstudio.com
42     tinytex       0.54   CRAN https://cran.rstudio.com
43       withr      3.0.2   CRAN https://cran.rstudio.com
44        xfun       0.49   CRAN https://cran.rstudio.com
45      xtable      1.8-4   CRAN https://cran.rstudio.com
46        yaml     2.3.10   CRAN https://cran.rstudio.com
```

**Comment by samperman** [comment] 2024-12-10 14:45
We think we have identified the cause of this and are looking into it. I don't have an ETA on when it will be fixed.

**Comment by rempsyc** [comment] 2024-12-16 20:19
Great, thanks. In the meanwhile, I suppose you wouldn't know of any temporary workarounds?

**Comment by samperman** [comment] 2024-12-17 19:41
I don't have a workaround, but! we have just pushed out a change that should address this, sorry for the delay here. Please let us know if things are still not working.

**Closed by samperman** 2024-12-17 19:41 UTC

**Comment by rempsyc** [comment] 2024-12-18 04:44
Great, thanks a lot! When I publish the toy app above, the app appears as published and running, but I get this error message:

> Error: An error has occurred. Check your logs or contact the app author for clarification.

This is the log:

``` console
── Preparing for deployment ────────────────────────────────────────────────────
✔ Re-deploying "test" using "server: shinyapps.io / username: rempsyc"
ℹ Looking up application with id "13562728"...
✔ Found application <https://rempsyc.shinyapps.io/test/>
ℹ Bundling 1 file: 'app.Rmd'
ℹ Capturing R dependencies
✔ Found 46 dependencies
✔ Created 28,051b bundle
ℹ Uploading bundle...
✔ Uploaded bundle with id 9538032
── Deploying to server ─────────────────────────────────────────────────────────
Waiting for task: 1490244578
  building: Building image: 11707242
  building: Fetching packages
  building: Installing packages
  building: Installing files
  building: Pushing image: 11707242
  deploying: Starting instances
  rollforward: Activating new instances
  terminating: Stopping old instances
── Deployment complete ─────────────────────────────────────────────────────────
✔ Successfully deployed to <https://rempsyc.shinyapps.io/test/>
Deployment completed: https://rempsyc.shinyapps.io/test/
```

The app works locally. Maybe I should open a new issue about this.

**Comment by rempsyc** [comment] 2024-12-18 04:57
Amazing, thanks a lot!
