### ISSUE TITLE
Unable to Bypass Auto-detect Locale

### ISSUE THREAD

**Issue by szmsu2011** [rstudio/rsconnect#536] opened 2021-08-14 18:46 UTC
Thanks for the continuous development of the package.

I was trying to deploy a shiny App in English to shinyapps.io. However, `rsconnect` kept overriding my R locale (en_NZ) with my Windows locale (zh_CN).

I immediately changed my Windows locale to en_NZ and republished the App, the resulting locale is still in zh_CN for some weird reasons.

Then, I noticed the possibility to bypass the auto-detection by configuring the `rsconnect.locale` option from #233, however, my naive assumption of `options(rsconnect.locale = "en_NZ")` or `options(rsconnect.locale = "en_US")` simply did not work.

Currently, my temporary solution is to call `Sys.setlocale("LC_ALL", "C")` before the app is called, but in such a way, all my date formatting from `lubridate` broke.

Could you please give an example on how to bypass the auto-detection/force the locale to be set to "en_NZ" or "en_US"?

Here are some more information:

```r
Sys.getlocale()
#> [1] "LC_COLLATE=English_New Zealand.1252;LC_CTYPE=English_New Zealand.1252;LC_MONETARY=English_New Zealand.1252;LC_NUMERIC=C;LC_TIME=English_New Zealand.1252"

sessionInfo()
#> R version 4.0.4 (2021-02-15)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19042)

#> Matrix products: default

#> locale:
#> [1] LC_COLLATE=English_New Zealand.1252  LC_CTYPE=English_New Zealand.1252   
#> [3] LC_MONETARY=English_New Zealand.1252 LC_NUMERIC=C                        
#> [5] LC_TIME=English_New Zealand.1252    

#> attached base packages:
#> [1] stats     graphics  grDevices datasets  utils     methods   base     

#> other attached packages:
#>  [1] tseries_0.10-48       janitor_2.1.0         colorspace_2.0-0     
#>  [4] lubridate_1.7.9       tsibble_1.0.0         leaflet_2.0.4.1      
#>  [7] sparkline_2.0         reactable_0.2.3.9000  echarts4r_0.4.0      
#> [10] rlang_0.4.10          shinyWidgets_0.6.0    htmlwidgets_1.5.3    
#> [13] forcats_0.5.0         stringr_1.4.0         dplyr_1.0.5          
#> [16] purrr_0.3.4           readr_1.3.1           tidyr_1.1.2          
#> [19] tibble_3.0.3          ggplot2_3.3.3         tidyverse_1.3.0      
#> [22] dashboardthemes_1.1.3 shinydashboard_0.7.1  shiny_1.6.0          

#> loaded via a namespace (and not attached):
#>  [1] httr_1.4.2        sass_0.3.1        jsonlite_1.7.2    modelr_0.1.8     
#>  [5] bslib_0.2.4       assertthat_0.2.1  TTR_0.23-6        blob_1.2.1       
#>  [9] renv_0.14.0       cellranger_1.1.0  pillar_1.4.6      backports_1.2.1  
#> [13] lattice_0.20-41   glue_1.4.1        quadprog_1.5-8    digest_0.6.25    
#> [17] promises_1.1.1    rvest_0.3.6       snakecase_0.11.0  htmltools_0.5.1.1
#> [21] httpuv_1.5.4      pkgconfig_2.0.3   broom_0.7.5       haven_2.3.1      
#> [25] xtable_1.8-4      scales_1.1.1      later_1.1.0.1     generics_0.0.2   
#> [29] ellipsis_0.3.1    withr_2.4.1       cli_2.3.1         quantmod_0.4.18  
#> [33] magrittr_1.5      crayon_1.3.4      readxl_1.3.1      mime_0.9         
#> [37] fs_1.5.0          anytime_0.3.9     xts_0.12.1        xml2_1.3.2       
#> [41] tools_4.0.4       hms_0.5.3         lifecycle_1.0.0   munsell_0.5.0    
#> [45] reprex_0.3.0      packrat_0.6.0     compiler_4.0.4    jquerylib_0.1.3  
#> [49] grid_4.0.4        rstudioapi_0.11   crosstalk_1.1.1   gtable_0.3.0     
#> [53] curl_4.3          DBI_1.1.0         R6_2.4.1          zoo_1.8-9        
#> [57] fastmap_1.0.1     stringi_1.4.6     Rcpp_1.0.5        vctrs_0.3.7      
#> [61] dbplyr_1.4.4      tidyselect_1.1.0
```

Thank you in advance.

**Comment by hadley** [comment] 2023-02-21 22:00
Closing as duplicate of #233

**Closed by hadley** 2023-02-21 22:00 UTC
Labels: bug, encoding :earth_asia:
