### ISSUE TITLE
MASS build fails during deploy

### ISSUE THREAD

**Issue by tstearns26** [rstudio/rsconnect#1050] opened 2024-03-08 20:36 UTC
I'm on R version 4.3.3, M2 with ventura, and I have a shiny app I'm attempting to deploy. I don't think it's related, but the app has a venv used with `reticulate`. I'm getting a failed deploy with the MASS build failing. 

```
ℹ Bundling 4865 files: app.R, ..., www/shiny_env/lib/python3.12/site-packages/pip-24.0.dist-info/WHEEL, and www/shiny_env/pyvenv.cfg
ℹ Capturing R dependencies with renv
✔ Found 59 dependencies
✔ Created 369,785,584b bundle
ℹ Uploading bundle...
✔ Uploaded bundle with id 8350684
── Deploying to server ─────────────────────────────────────────────────────────
Waiting for task: 1392528151
  building: Processing bundle: 8350684
  building: Parsing manifest
  building: Building image: 10110068
  building: Building package: MASS
## Begin Task Log ##############################################################
## End Task Log ################################################################
Error: Unhandled Exception: child_task=1392528152 child_task_status=failed: Error building image: Error building MASS (7.3-60.0.1). Build exited with non-zero status: 127
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
```

Any advice on this? I've update and reinstall MASS with no luck.

**Comment by aronatkins** [comment] 2024-03-08 21:27
This is a duplicate of https://github.com/rstudio/rsconnect/issues/1048

shinyapps.io does not yet support R 4.3.3. Please use the community site for additional questions and details: https://community.rstudio.com/c/shiny/shinyappsio/24

CC @ssinnott

**Closed by aronatkins** 2024-03-08 21:27 UTC
