### ISSUE TITLE
Deploying in Connect: Error in eval(x, envir = envir)

### ISSUE THREAD

**Issue by csgillespie** [rstudio/rsconnect#429] opened 2020-05-22 07:36 UTC
I have two Rmd files. File 1 the master:
```
>   ---
>    title: "Test"
>    output: html_document
>    ---
> 
>    ```{r, echo = FALSE, include=TRUE}
>    child_docs <- "header.Rmd"
>    ```
>    ```{r, run_child, child = child_docs}
>    ```
```
File 2: `header.Rmd`

```
# Report 1
Chunk number 1
```

---
I can knit the documents without error. I can also deploy the document to Connect, but I get the error:

```
Preparing to deploy document...DONE
Uploading bundle for document: 18...[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata,
  e.g. by using --metadata pagetitle="..." on the command line.
  Falling back to 'header.utf8'
Error in eval(x, envir = envir) : object 'child_docs' not found
DONE
Deploying bundle: 42 for document: 18 ...
```
Although it states that `child_docs` isn't found, it still deploys. Any ideas?

---

Originally raised at https://community.rstudio.com/t/deploying-in-connect-error-in-eval-x-envir-envir/67038

**Comment by jmcphers** [comment] 2020-07-23 21:24
Can you attach a verbose publish log if you're still seeing this? (Go to Global Options -> Publishing and tick "show diagnostic information when publishing")

**Comment by aronatkins** [comment] 2021-01-27 20:39
Given an `index.Rmd`:

````markdown
---
title: "rmarkdown with a child document"
output: html_document
---

```{r, echo = FALSE, include=TRUE}
child_docs <- "header.Rmd"
```

```{r, run_child, child = child_docs}
```
````

And a `header.Rmd` file:

````markdown
this is the header.Rmd file
````

The output comes from the `packrat:::fileDependencies` helpers.

```
> packrat:::fileDependencies("header.Rmd")
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'header.utf8' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
[1] "rmarkdown"
> packrat:::fileDependencies("index.Rmd")
Quitting from lines 13-13 (index.Rmd) 
Error in eval(x, envir = envir) : object 'child_docs' not found
```

The title warning from the `header.Rmd` can be avoided if we give it a dummy YAML preamble with title.

**Comment by aronatkins** [comment] 2021-01-27 21:17
Errors from the `index.Rmd` are because we do not really evaluate the chunks when scanning for dependencies. Somehow, we're still trying to use these variable references.

Narrower function calls that produce the same output for `index.Rmd`:

```
> packrat:::fileDependencies.Rmd.tangle("index.Rmd")
Error in eval(x, envir = envir) : object 'child_docs' not found
NULL
> packrat:::fileDependencies.Rmd.evaluate("index.Rmd")
Quitting from lines 13-13 (index.Rmd) 
NULL
```

**Comment by aronatkins** [comment] 2022-02-15 14:04
This problem was caused by using rmarkdown::render to analyze R Markdown files for dependencies.

We believe that this is resolved with https://github.com/rstudio/packrat/pull/647.

**Closed by aronatkins** 2022-02-15 14:04 UTC
Labels: dependencies
