### ISSUE TITLE
HTTP 500 error when connecting new account

### ISSUE THREAD

**Issue by pyltime** [rstudio/rsconnect#75] opened 2015-10-12 16:44 UTC
Steps to repro:
1.) Turn on RStudio Connect UI and create account on beta.rstudioconnect.com
2.) Open .Rmd file and click Publish button
3.) Choose RStudio Connect, click through to "Connect Publishing Account"
4.) enter address, choose "server supports secure connections"
5.) "Sign in with Google" page pops up in RStudio Browser window, click "Sign in with Google"

This caused the following output to repeat endlessly in my RStudio Console:

```
* Connection #0 to host beta left intact
*   Trying 54.237.109.157...
* Connected to beta  port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *
* Server certificate: Go Daddy Secure Certificate Authority - G2
> GET /__api__/users/current/ HTTP/1.1
User-Agent: rsconnect/0.4.1.4
Accept: */*
Date: Mon, 12 Oct 2015 16:40:27 GMT
X-Auth-Token: Te280de2fbfb5eb88b06018e3458f1aca
X-Auth-Signature: EtV1bcrWNRqrbNI9DzgmskQK33t4aT9HkBJzaI2LcSIIzX9FR7yzLHli1O2df0J8VCnjQdrhpfjMJGbUfe22Gv7vZsWUguYpNZGGnQFlybNP7sVjn4rvdWBJ6zhF61vXUKR5quS7OtEbIVyEpBn9mBg3CWbJscHeeegNLU9OzHH8vO86BZETWsvC2dPbZLccjH8htKhD4UMBHyvxnwwCVJszpRZmdpeskoVZOIgcuQ4E5PzN/l6OyWgLay6dSyhn7SkWir+PxQ3LjqINtTcVOFXWTNI9bIs35b+f+knZbAzMPBQMAO3sERyqbRFkdNt9wxI2LruDkF7YC3mkOXi6PA==
X-Content-Checksum: 1B2M2Y8AsgTpgAmY7PhCfg==

< HTTP/1.1 500 Internal Server Error
< Content-Type: text/html;charset=utf-8
< Server: RStudio Connect Server v0.3.797
< Date: Mon, 12 Oct 2015 16:40:27 GMT
< Content-Length: 823
```

and the following error in my Chrome window:
"An error has occurred

Attempt to use invalid state"

Eventually I was able to get it working by clicking the "Confirm account" link in the RStudio dialog, which opened the sign-in page in Chrome where I was then able to sign in.

**Comment by jmcphers** [comment] 2015-10-12 16:51
The IDE's account connector works by polling this endpoint:

    /__api__/users/current/

The polling happens here:

https://github.com/rstudio/rsconnect/blob/362b845dd798802f57ae9f2c88818047d655028a/R/accounts.R#L99

It expects that either:
a) the endpoint will begin working (once the user signs in), or
b) the user will cancel the auth by closing the RStudio browser window

Off the top of my head - it looks like the problem is that the response code for `GET /__api__/users/current/` isn't 401 but 500. 

https://github.com/rstudio/rsconnect/blob/362b845dd798802f57ae9f2c88818047d655028a/R/accounts.R#L282

Maybe something changed in the HTTP status codes we return for unauth'ed requests?

**Comment by trestletech** [comment] 2015-10-12 16:53
We have nothing in the log between 16:34 and 16:43 on the server, sadly. 

@aronatkins had done some rewiring on the status codes recently -- it's possible that we might have nudged one of these.

**Comment by trestletech** [comment] 2015-10-12 19:17
Actually now that I look at the message it definitely looks like a real error (a legitimate 500) not a false alarm. @CBarraford the error's coming from https://github.com/rstudio/connect/blob/master/src/connect/auth/providers/oauth2/oauth2.go#L267 Can you think of any reason why we wouldn't get a `state` off of an oauth request?

**Comment by CBarraford** [comment] 2015-10-12 19:20
we could be chopping it off.
https://github.com/rstudio/connect/pull/781

**Comment by CBarraford** [comment] 2015-10-12 19:22
or https://github.com/rstudio/connect/commit/1a64bdeb7dc0dcf0ce71b5b77fe1e669723dbffc

**Comment by CBarraford** [comment] 2015-10-12 19:26
nope i guess not, we are still adding state. https://github.com/rstudio/connect/blob/master/src/connect/auth/providers/oauth2/oauth2.go#L216

**Comment by trestletech** [comment] 2015-10-12 19:32
@pyltime no chance you took a lunch break in the middle of doing this, is there? We do flush some state out after one hour. i.e. if you sat on the login page for an hour before clicking through the Google stuff, we'd expect this error.

**Comment by pyltime** [comment] 2015-10-12 20:12
Nope, this was all within a minute or so.

**Comment by jmcphers** [comment] 2019-11-13 20:41
I believe we eventually discovered that this was due to a bug in rsconnect's handling of empty responses.

**Closed by jmcphers** 2019-11-13 20:41 UTC
