### ISSUE TITLE
error with connectUser when using http url redirected to https

### ISSUE THREAD

**Issue by cderv** [rstudio/rsconnect#327] opened 2018-12-12 18:30 UTC
Hi, 

In my internal setup of Rstudio Connect I encountered a strange behaviour when testing to connect a user using the 'http' url not the https, but with my server configure to redirect to https. 

I reproduced in with beta.rstudioconnect.com

## Step to reproduce

```r
rsconnect::addServer('http://beta.rstudioconnect.com', "beta.rstudioconnect)
rsconnect::connectUser(server = "beta.rstudioconnect")
> Error: $ operator is invalid for atomic vectors
```

The error happens in `rsconnect:::getAuthToken` where at some point a `POST_JSON(service, authInfo, "/tokens", token)` is called. The response is 

```r
Browse[4]> response
$`req`
$`req`$`protocol`
[1] "http"

$`req`$host
[1] "beta.rstudioconnect.com"

$`req`$port
[1] ""

$`req`$method
[1] "POST"

$`req`$path
[1] "/tokens"


$status
[1] 307

$location
[1] "https://beta.rstudioconnect.com/tokens"

$contentType
[1] "text/plain"

$content
[1] ""
```

So this is a redirect call that `rsconnect:::handleResponse` does not seem to handle as it goes in here
https://github.com/rstudio/rsconnect/blob/8e61e0b6784ff576f03bafe28abe477554fd1dc4/R/client.R#L52-L58

and `response$content` is `""` so `getAuthToken` gets an error. 

The redirect is not followed... 

Am I missing something ? 

Surely, the https url is working and it is not blocking. I just expected the http url to work, or at least to give an explicit error message.

let me know if I could help investigate.

Thanks.

**Comment by hadley** [comment] 2023-02-21 16:48
Duplicate of #674, which has a little more info about the root cause.

**Closed by hadley** 2023-02-21 16:48 UTC
Labels: accounts
