### ISSUE TITLE
Listing applications shows applications from rstudio.cloud

### ISSUE THREAD

**Issue by mcbex** [rstudio/rsconnect#483] opened 2021-02-02 18:36 UTC
To reproduce: 

Connect to a shinyapps.io account that has also been used to create projects in rstudio.cloud
rsconnect::applications('my-account')

Notice the output includes shiny apps deployed on shinyapps.io and also applications with names like this: 

4    11127 2df333d3fb0b4cf59a07d734c3137cd0-project-source
5    13858 261ebb3063c54b86a16d402a319a20d4-project-source
6    13907 3cfe0639082c433ab4382139ce37bb81-project-source
7    13931 33cd01c22a53468bbd76020771045e07-project-source
8    17156 8e6e53b5024747c09f49e01879b16b3f-project-source

These are from rstudio.cloud and don't have meaningful names. The expected output from this command probably shouldn't include them.

**Comment by kippandrew** [comment] 2021-02-02 23:14
I think we add a filter for application type here: https://github.com/rstudio/rsconnect/blob/master/R/lucid.R#L60

**Comment by hadley** [comment] 2023-02-28 23:36
@kippandrew any thoughts on how to reproduce this? I have shinyapps.io and rstudio.cloud accounts for `hadley@posit.co`, but `rsconnect::applications(server = "shinyapps.io")` only lists my shiny apps.

**Comment by hadley** [comment] 2023-02-28 23:53
I also tried deploying a shiny app to posit.cloud, in case that was the issue, and I don't see it listed.

**Comment by aronatkins** [comment] 2023-03-01 01:30
@hadley This may have been resolved with https://github.com/rstudio/rsconnect/pull/627

**Comment by hadley** [comment] 2023-03-01 13:12
Ok, great, looks like we can close it then.

**Closed by hadley** 2023-03-01 13:12 UTC
Labels: bug, shinyapps.io :medal_military:
