### ISSUE TITLE
Attempting to Publish a document to RStudio Connect from the home directory of the IDE results in an error when R version is set to 3.6.3.

### ISSUE THREAD

**Issue by R-Hannibal** [rstudio/rsconnect#441] opened 2020-07-10 21:33 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 1.3.959
    OS Version      : Windows 10 x64
    R Version       : 3.6.3

### Steps to reproduce the problem

1. Open the IDE with R version set to 3.6.3.
2. Open > Save > Knit a new RMarkdown file to the IDE home directory (this can be checked by entering `path.expand("~/")` in the console.
3. Publish the document to RStudio Connect.

### Describe the problem in detail
The following error is thrown in the Deploy pane and the document fails to publish. This ONLY occurs if the document is in the home directory, saving it to another location and then publishing it works.
```
Error in rsconnect::deployApp(appDir = "~/", appFileManifest = "C:/Users/iredh/AppData/Local/Temp/3c16-d58b-417a-6940",  : 
  C:\Users\iredh\Documents\ does not exist
Execution halted
```

### Describe the behavior you expected
Documents publish successfully to RStudio Connect when saved in or out of the home directory.

### Note(s)

- Link to the Slack message where this issue was originally discussed for additional info [HERE](https://rstudio.slack.com/archives/C0DAAVDJQ/p1594411155136600).

**Comment by hadley** [comment] 2023-02-23 20:28
From slack discussion, this is probably about trailing slashes on windows, so this is duplicate of #213.

**Comment by hadley** [comment] 2023-02-23 21:12
And resolved the same way, with `normalizePath()`.

**Closed by hadley** 2023-02-23 21:12 UTC
Labels: bug, deploy :bouncing_ball_person:
