### ISSUE TITLE
At deploy time, detect and warn when an Rmd file contains relative paths in directories above it

### ISSUE THREAD

**Issue by ajmcoqui** [rstudio/rsconnect#101] opened 2016-05-23 18:58 UTC
In shinyapps.io, you cannot load an Rmd file that contains relative paths in directories above the one in which the Rmd file resides; the relative paths must be at the same level or below. You can use these uphill references locally, but after deploying it, loading it fails.  Users find it confusing to be able to compile a .Rmd file using resources from directories above the one in which the .Rmd file resides, only to have it fail during deployment.

**Comment by kevinushey** [comment] 2016-05-23 21:47
Relative paths should be reported already; this works in the simple cases -- e.g. I see this after attempting to deploy a dummy application:

![screen shot 2016-05-23 at 2 47 00 pm](https://cloud.githubusercontent.com/assets/1976582/15485639/40055d50-20f5-11e6-9eea-28e2157e0a1e.png)

Do we have a reproducible example for this one?

**Comment by ajmcoqui** [comment] 2016-05-25 00:19
The scenario is a single project with multiple sub-directories that each contain R presentations.  At the same level as the subdirectories, there are dirs for data, images, scripts, css, etc.  A simplified structure would be:

.Rproj
data
 |_ data.csv
presentation1
 |_ Nested.Rmd

The use case here is a user with multiple presentations that all use the same CSS files, images, data, etc.  The user doesn't want to copy the same set of files into separate projects, so she has one set of static files and multiple presentations that use them, stored in subdirs of a single project.

Nested.Rmd references ../data/data.csv.  If you knit Nested.Rmd within RStudio, it works.  If you deploy the app to shinyapps.io from within the presentation1 directory, the deployment succeeds, but the app shows an immediate error:  Error: cannot open the connection

See https://agadrow.shinyapps.io/presentation1/  I can share the code, but it's just the vanilla example code you get when you create a new R Markdown file in RStudio, of type Shiny Presentation.  The only thing I modified was the "R Output" section, which I replaced with a simple read in of a data file:

## R Output

```{r}
data <- read.csv("../data/data.csv")
summary(data)
```

**Comment by jjallaire** [comment] 2016-05-25 11:23
This is tied up in how runtime: shiny works (which is that it copies the
dependent files into a separate directory). Given that there is no way that
relative references above the current directory will ever work in runtime:
shiny. Overall this business of copying files to another directory has
caused many problems and I think we wish we didn't have to do it but that's
how the system works right now.

**Comment by ajmcoqui** [comment] 2016-05-25 13:10
Some users have been getting around it with symlinks per this issue: https://github.com/rstudio/rmarkdown/issues/504  But is there any way we can detect this structure and warn the user at deploy time, before it gets to the point of showing an error in the app on shinyapps.io?

**Comment by jjallaire** [comment] 2016-05-25 13:12
We could definitely update the linter to detect this. Let's keep a list of
items we should add to the linter then we can schedule that work for after
useR.

**Comment by MadNietzsche** [comment] 2018-05-21 14:17
Are there any updates related to this issue?

**Comment by hadley** [comment] 2023-02-21 17:35
Closing since it's been 6+ years, and it looks like the linter already catches the most common case.

**Closed by hadley** 2023-02-21 17:35 UTC
Labels: linting :coat:
