### ISSUE TITLE
Quarto error message is too vague for new Quarto users

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rsconnect#724] opened 2023-03-02 15:31 UTC
A lot of newer Quarto folks are not likely to be able to parse: 

> Please supply a path to a quarto binary in `quarto`

So adding to docs or error messages about `Sys.which("quarto")`, `quarto::quarto_path()`, or saying to from your terminal execute `which quarto` would be more clear.

The current error message for Quarto content without a Quarto path should probably say to use `quarto::quarto_path()` as recommended elsewhere:

https://github.com/rstudio/rsconnect/blob/935f25e66b588cda49d7915ac369869c6a7079a3/R/deployApp.R#L122-L124

Rather than the rather vague error message:

```
! Can't deploy Quarto content when `quarto` is `NULL`.
i Please supply a path to a quarto binary in `quarto`.
```

As a side-effect, it may also be worth adding `quarto` R package as a suggests dependency, so that it's already around for most users.

**Comment by jthomasmock** [comment] 2023-03-02 15:32
Example from slack:

> I have some slides due for a conf, and having trouble running: rsconnect::writeManifest()
> I get this:
>
> ```
> Error in inferAppMode(appDir = appDir, appPrimaryDoc = appPrimaryDoc,  :
>  Attempting to deploy Quarto content without Quarto metadata. Please provide the path to a > quarto binary to the 'quarto' argument.
> ```
>
> Didn't see much online for that error other than this page https://github.com/cran/rsconnect/blob/master/R/bundle.R
> I followed the steps here: https://quarto.org/docs/publishing/rstudio-connect.html#publishing-from-git

I'll also x-post to quarto-web

**Comment by hadley** [comment] 2023-03-02 16:16
I think this is basically a duplicate of #658; see proposal in https://github.com/rstudio/rsconnect/issues/658#issuecomment-1435129869

**Closed by hadley** 2023-03-02 16:16 UTC
