### ISSUE TITLE
Plots from code chunks with spaces in name do not deploy properly in ShinyApps.io

### ISSUE THREAD

**Issue by sharlagelfand** [rstudio/rsconnect#153] opened 2017-01-29 07:37 UTC
When I deploy an app to ShinyApps.io and a code chunk with a space in its name has a plot, the plot does not render on ShinyApps.io

**Without a space**

    ---
    output: 
      flexdashboard::flex_dashboard:
        orientation: columns
        vertical_layout: fill
    ---
    
    ```{r ChunkName}
    plot(rnorm(10))
    ````

renders fine in RStudio/browser and deploys fine to ShinyApps.io -- https://sharlagelfand.shinyapps.io/no_space_in_chunkname/

**But with a space...**

    ---
    output: 
      flexdashboard::flex_dashboard:
        orientation: columns
        vertical_layout: fill
    ---
    
    ```{r Chunk Name}
    plot(rnorm(10))
    ````

Also renders fine in RStudio/browser, but the image doesn't work properly on ShinyApps.io, just empty https://sharlagelfand.shinyapps.io/space_in_chunk_name/

`rsconnet::showLogs()` shows 

    Warning in normalizePath(path, winslash = winslash, mustWork = mustWork) :
    path[1]="figure-html/Chunk Name-1.mb.png": No such file or directory

**Comment by jjallaire** [comment] 2017-01-29 17:06
@jspiewak and @kippandrew Any reason you can think of that this would be happening?

**Comment by jspiewak** [comment] 2017-01-30 14:33
Because the file has a space in the name.
Easily reproducible locally on a Mac with the addition of `runtime: shiny`

**Comment by jjallaire** [comment] 2017-01-30 15:15
@sharlagelfand It looks like chunk names with spaces just don't work right now.

**Comment by jjallaire** [comment] 2017-01-30 15:23
@jmcphers Is this something which would be straightforward to overcome?

**Comment by jmcphers** [comment] 2017-01-30 20:29
That's a good question! I spent some time debugging this and didn't find an obvious culprit in rmarkdown; it looks like the images are getting correctly rendered and placed, but that Shiny isn't serving them (was able to reproduce the problem in a simple Shiny app). I've gotten in touch with the Shiny team and will file an issue over there if that turns out to be the problem.

**Comment by jmcphers** [comment] 2017-01-30 23:33
Appears to be due to https://github.com/rstudio/shiny/issues/1565.

**Comment by sharlagelfand** [comment] 2017-02-01 07:16
I'll get used to not using a space, and start putting `runtime: shiny` in my code -- thanks all!

**Comment by jmcphers** [comment] 2019-11-14 00:24
Fixed in https://github.com/rstudio/shiny/issues/1565.

**Closed by jmcphers** 2019-11-14 00:24 UTC
