### ISSUE TITLE
Bug with locale setting?

### ISSUE THREAD

**Issue by dominicroye** [rstudio/rsconnect#562] opened 2022-01-08 10:48 UTC
Hi, 
 
I just updated my app on https://xeo81.shinyapps.io/MeteoExtremosGalicia/, but since the update, the local definition isn't right on the shinyapp server. It shouldn't be English. This causes problems in ggplot and the months labels are in English instead of Spanish.

My session info is the following:

```
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252   
[3] LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                  
[5] LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
 [1] gfonts_0.1.3       rlang_0.4.12       metR_0.11.0       
 [4] ggtext_0.1.1       fresh_0.2.0        metathis_1.1.1    
 [7] sf_1.0-5           leafpop_0.1.0      leaflet_2.0.4.1   
[10] png_0.1-7          cowplot_1.1.1      ggthemes_4.2.4    
[13] rdrop2_0.8.2.1     RColorBrewer_1.1-2 showtext_0.9-4    
[16] showtextdb_3.0     sysfonts_0.8.5     lubridate_1.8.0   
[19] forcats_0.5.1      stringr_1.4.0      dplyr_1.0.7       
[22] purrr_0.3.4        readr_2.1.1        tidyr_1.1.4       
[25] tibble_3.1.6       ggplot2_3.3.5.9000 tidyverse_1.3.1   
[28] shiny_1.7.1.9002  

loaded via a namespace (and not attached):
 [1] colorspace_2.0-2   ellipsis_0.3.2     class_7.3-19      
 [4] rprojroot_2.0.2    rsconnect_0.8.26   base64enc_0.1-3   
 [7] fs_1.5.2           gridtext_0.1.4     rstudioapi_0.13   
[10] httpcode_0.3.0     proxy_0.4-26       remotes_2.4.2     
[13] fansi_0.5.0        xml2_1.3.3         cachem_1.0.6      
[16] knitr_1.37         pkgload_1.2.4      jsonlite_1.7.2    
[19] broom_0.7.11       dbplyr_2.1.1       compiler_4.1.2    
[22] httr_1.4.2         backports_1.4.1    assertthat_0.2.1  
[25] fastmap_1.1.0      cli_3.1.0          later_1.3.0       
[28] htmltools_0.5.2    prettyunits_1.1.1  tools_4.1.2       
[31] gtable_0.3.0       glue_1.6.0         Rcpp_1.0.7        
[34] cellranger_1.1.0   vctrs_0.3.8        crul_1.2.0        
[37] svglite_2.0.0      crosstalk_1.2.0    xfun_0.29         
[40] ps_1.6.0           testthat_3.1.1     rvest_1.0.2       
[43] mime_0.12          lifecycle_1.0.1    devtools_2.4.3    
[46] scales_1.1.1       hms_1.1.1          promises_1.2.0.1  
[49] curl_4.3.2         memoise_2.0.1      sass_0.4.0        
[52] stringi_1.7.6      desc_1.4.0         e1071_1.7-9       
[55] checkmate_2.0.0    pkgbuild_1.3.1     pkgconfig_2.0.3   
[58] systemfonts_1.0.3  htmlwidgets_1.5.4  tidyselect_1.1.1  
[61] processx_3.5.2     magrittr_2.0.1     R6_2.5.1          
[64] generics_0.1.1     DBI_1.1.2          pillar_1.6.4      
[67] haven_2.4.3        withr_2.4.3        units_0.7-2       
[70] modelr_0.1.8       crayon_1.4.2       uuid_1.0-3        
[73] KernSmooth_2.23-20 utf8_1.2.2         tzdb_0.2.0        
[76] usethis_2.1.5      grid_4.1.2         readxl_1.3.1      
[79] data.table_1.14.2  callr_3.7.0        reprex_2.0.1      
[82] digest_0.6.29      classInt_0.4-3     xtable_1.8-4      
[85] httpuv_1.6.5       brew_1.0-6         openssl_1.4.6     
[88] munsell_0.5.0      sessioninfo_1.2.2  askpass_1.1 
```

Thanks!

**Comment by kippandrew** [comment] 2022-01-11 22:52
If you have a subscription to shinyapps.io, I recommend opening a ticket with the support team. Otherwise, do you mind sharing the output from the deployment? It might shed light on why the locale isn't being detected properly.

**Comment by hadley** [comment] 2023-02-20 21:42
Duplicate of #542, I think.

**Closed by hadley** 2023-02-20 21:42 UTC
