### ISSUE TITLE
Could not find files to deploy

### ISSUE THREAD

**Issue by xtimbeau** [rstudio/rsconnect#524] opened 2021-06-25 11:32 UTC
When a file inside a directory for a shiny app is named with specials characters (é for instance), then the deployApp() is failing with the following message:
`Error in if (info$isdir) { : missing value where TRUE/FALSE needed`
Removing or renaming makes everything back to normal.

**Comment by kevinushey** [comment] 2021-06-25 17:53
What operating system are you using? Presumedly, Windows? Can you share the output of `list.files()` in the folder containing that file?

I suspect the issue here is that `list.files()` fails to list that file, since that function only supports paths that can be represented in the native encoding. A workaround would be to use the [fs](https://cran.r-project.org/web/packages/fs/index.html) package instead.

**Comment by xtimbeau** [comment] 2021-06-25 18:02
Yes, windows 10 indeed. I should have been more specific !
I did a small reprex : from RStudio (W10, RStudio 1.4.1717, R 4.1.0) create a shiny web app project, inside a test folder with inside a text file named hé.txt. 
With é it fails to deploy, without, it works. Note that it is only a file inside `test` that has special characters, `test` itself is clean.
Here is the console  output. The first line is the publish error.
```
Error in if (info$isdir) { : missing value where TRUE/FALSE needed
> list.files()
[1] "app.R"      "test"       "test.Rproj"
> list.files("test")
[1] "hÃ©.txt"
> 
```

**Comment by kevinushey** [comment] 2021-06-25 18:25
Interesting... Have you enabled the OS-level (experimental) UTF-8 support for Windows on your machine? The issue is that this looks like a UTF-8 path that's being mis-interpreted in the local (latin-1) code page. For example:

```
> file <- "hÃ©.txt"
> file
[1] "hÃ©.txt"
> Encoding(file) <- "UTF-8"
> file
[1] "hé.txt"
```

**Comment by xtimbeau** [comment] 2021-06-25 19:03
yes I could have set up and then back down due to some strange behaviors
utf-8 and w10 is a mess of epic proportion

Le ven. 25 juin 2021 à 20:25, Kevin Ushey ***@***.***> a
écrit :

**Comment by hadley** [comment] 2023-02-20 22:31
I've rewritten the code that does this checking and R 4.2.0 should also help, so I'm going to close this issue. Please feel free to open a new issue if it re-occurs.

**Closed by hadley** 2023-02-20 22:31 UTC
