### ISSUE TITLE
rsconnect::appDependencies evaluates eval parameter in rmarkdown chunks and might produce warnings

### ISSUE THREAD

**Issue by dirkschumacher** [rstudio/rsconnect#459] opened 2020-09-29 16:48 UTC
# Context
I have an rmarkdown file that uses the `eval` parameters in chunks to control which chunks get evaluated. The idea is for that specific application that the code envoking `rmarkdown::render` can control what chunks will be evaluated instead of the report itself in order to keep the login in the markdown file as small as possible.

# Problem
When `rsconnect::appDependencies()` is invoked it evaluates the code in each eval parameter and thus producing a warning. These warnings are in particularly genereted during deployments to RStudio Connect. / shinyapps.io. Nothing breaks though.

# Reproducible example

Create a file "test.Rmd" with a single chunk

````markdown
```{r test, eval=show_chunk} 
summary(cars)
```
````

then:

```
> rsconnect::appDependencies()
Error in eval(x, envir = envir) : object 'show_chunk' not found
```

Here is an example of how it is used:

```R
rmarkdown::render("test.Rmd", envir = list(show_chunk = TRUE))
rmarkdown::render("test.Rmd", envir = list(show_chunk = FALSE))
```

# Potential solution

* One option could be to `suppressWarnings` when evaluating `eval`, but this might have other unintented sideeffects.

**Comment by dirkschumacher** [comment] 2020-09-30 19:01
Might be related to #429

**Comment by jmcphers** [comment] 2021-02-25 00:37
Yes, this is likely a side effect of the dependency discovery scan.

Do you see the same error when you run `rmarkdown::find_external_resources()` on your doc?

**Comment by aronatkins** [comment] 2022-02-15 14:03
This problem was caused by using rmarkdown::render to analyze R Markdown files for dependencies.

We believe that this is resolved with https://github.com/rstudio/packrat/pull/647.

**Closed by aronatkins** 2022-02-15 14:03 UTC
Labels: dependencies
