### ISSUE TITLE
Basic RMD flagged as a site

### ISSUE THREAD

**Issue by trestletech** [rstudio/rsconnect#117] opened 2016-09-15 15:19 UTC
@tareefk found that when he creates a new, empty project in IDE 1.0.7 and then creates the sample RMD, when he goes to publish it it gets flagged as a site by rsconnect.

From the bundle RSC got:

```
"metadata" : {
        "appmode" : "rmd-static",
        "primary_rmd" : "Base_Rmarkdown.Rmd",
        "primary_html" : null,
        "content_category" : "site",
        "has_parameters" : false
    },
```

Deploy log below, bundle uploaded to RSC attached.

```
Preparing to deploy site...DONE
Uploading bundle for site: 1233...DONE
Deploying bundle: 1790 for site: 1233 ...
Bundle requested R version 3.3.1; using /opt/R/3.3.1/bin/R which has version 3.3.1
2016/09/15 15:02:35.997686287 Installed packrat SHA is 5c45d48a3825eb392d618eeb383b0cdcbcccb4a3; packaged packrat SHA is 5c45d48a3825eb392d618eeb383b0cdcbcccb4a3
2016/09/15 15:02:35.999209913 Packrat is up-to-date.
2016/09/15 15:02:36.011567127 R version: 3.3.1
2016/09/15 15:02:36.011630514 packrat version: 0.4.8.1
2016/09/15 15:02:36.150742328 Audited package hashes with local packrat installation.
2016/09/15 15:02:37.987432210 Installing Rcpp (0.12.7) ... 
2016/09/15 15:02:38.016734520 	OK (symlinked cache)
2016/09/15 15:02:38.017035237 Installing assertthat (0.1) ... 
2016/09/15 15:02:38.111575286 	OK (symlinked cache)
2016/09/15 15:02:38.111900802 Installing base64enc (0.1-3) ... 
2016/09/15 15:02:38.133194488 	OK (symlinked cache)
2016/09/15 15:02:38.133472541 Installing bitops (1.0-6) ... 
2016/09/15 15:02:38.150211642 	OK (symlinked cache)
2016/09/15 15:02:38.150517061 Installing digest (0.6.10) ... 
2016/09/15 15:02:38.173215503 	OK (symlinked cache)
2016/09/15 15:02:38.173565886 Installing formatR (1.4) ... 
2016/09/15 15:02:38.216806364 	OK (symlinked cache)
2016/09/15 15:02:38.217120441 Installing highr (0.6) ... 
2016/09/15 15:02:38.246470578 	OK (symlinked cache)
2016/09/15 15:02:38.246788007 Installing jsonlite (1.0) ... 
2016/09/15 15:02:38.267157939 	OK (symlinked cache)
2016/09/15 15:02:38.267497204 Installing lazyeval (0.2.0) ... 
2016/09/15 15:02:38.290752052 	OK (symlinked cache)
2016/09/15 15:02:38.291073789 Installing magrittr (1.5) ... 
2016/09/15 15:02:38.316045925 	OK (symlinked cache)
2016/09/15 15:02:38.316434958 Installing mime (0.5) ... 
2016/09/15 15:02:38.335742181 	OK (symlinked cache)
2016/09/15 15:02:38.336022934 Installing packrat (0.4.7-1) ... 
2016/09/15 15:02:38.354300389 	OK (symlinked cache)
2016/09/15 15:02:38.354573352 Installing stringi (1.1.1) ... 
2016/09/15 15:02:38.382733607 	OK (symlinked cache)
2016/09/15 15:02:38.383027156 Installing yaml (2.1.13) ... 
2016/09/15 15:02:38.404549807 	OK (symlinked cache)
2016/09/15 15:02:38.404560336 Installing caTools (1.17.1) ... 
2016/09/15 15:02:38.420116000 	OK (symlinked cache)
2016/09/15 15:02:38.420396298 Installing htmltools (0.3.5) ... 
2016/09/15 15:02:38.445845748 	OK (symlinked cache)
2016/09/15 15:02:38.446119669 Installing tibble (1.2) ... 
2016/09/15 15:02:38.476800549 	OK (symlinked cache)
2016/09/15 15:02:38.477071258 Installing markdown (0.7.7) ... 
2016/09/15 15:02:38.497590304 	OK (symlinked cache)
2016/09/15 15:02:38.497868428 Installing stringr (1.1.0) ... 
2016/09/15 15:02:38.524933045 	OK (symlinked cache)
2016/09/15 15:02:38.525197759 Installing evaluate (0.9) ... 
2016/09/15 15:02:38.543984101 	OK (symlinked cache)
2016/09/15 15:02:38.544270559 Installing knitr (1.14) ... 
2016/09/15 15:02:38.577993715 	OK (symlinked cache)
2016/09/15 15:02:38.578262400 Installing rmarkdown (1.0.9013) ... 
2016/09/15 15:02:38.607871994 	OK (symlinked cache)
2016/09/15 15:02:38.609530741 Promoting newly installed packages to the package cache.
Completed packrat build against R version: '3.3.1'
Building document...
2016/09/15 15:02:39.526612200 Using Packrat dir /opt/rstudio-connect/mnt/report/packrat/lib/x86_64-pc-linux-gnu/3.3.1
2016/09/15 15:02:39.545919924 LANG: en_US.UTF-8
2016/09/15 15:02:39.546148978 R version: 3.3.1
2016/09/15 15:02:39.546236037 rmarkdown version: 1.0.9013
2016/09/15 15:02:39.546280916 knitr version: 1.14
2016/09/15 15:02:40.182944219 Error in rmarkdown::render_site(envir = new.env()) :
2016/09/15 15:02:40.182960246   No site generator found.
2016/09/15 15:02:40.183110417 Calls: local ... eval.parent -> eval -> eval -> eval -> eval -> <Anonymous>
2016/09/15 15:02:40.183199140 Execution halted
Site deployment failed with error: exit status 1
```

[app-1792-3544.tar.gz](https://github.com/rstudio/rsconnect/files/474973/app-1792-3544.tar.gz)

**Comment by trestletech** [comment] 2016-09-15 15:20
We circumstantially believe this occurs in IDE 1.0.16, as well.

**Comment by jmcphers** [comment] 2016-09-15 17:05
I could not reproduce this. :-/ Has anyone else seen it? For more diagnostics we should look at:

1) a .tar.gz containing the project directory
2) the full path of the saved .Rmd if it's not inside the project directory

**Comment by trestletech** [comment] 2016-09-15 17:12
@cchaudhari were you able to reproduce this?

**Comment by ChaitaC** [comment] 2016-09-15 17:18
@trestletech, I am unable to reproduce when I follow Tareef's steps (Create new, empty project-->then trying to deploy sample RMD)

I am only able to reproduce the error if I add a  _site.yml file in the same directory. (But note that Tareef's directory didn't have a _site.yml file)

**Comment by jjallaire** [comment] 2016-09-15 17:44
I can't reproduce this either.

J

**Comment by ajmcoqui** [comment] 2016-09-27 15:44
I just hit this, with @ChaitaC watching over my shoulder.  Steps to reproduce:

1.  Open IDE (I'm using the latest preview, 1.0.27)
2.  File > New Project...
3.  New Directory > Empty Project > give it a name, deselect "Create a git repository", and select "Open in new session" > Create Project
4.  File > New File > R Markdown...
5.  Install Required Packages > Yes
6.  Give the file a name and leave HTML output selected > OK
7. Save doc
8. Knit
9. Publish from within rendered doc
10. Install Required Packages > Yes
11. Publish to RStudio Connect
12. Publish document with source code
13. Destination account > beta server
14. Publish
15.  Error in Deploy pane:
`2016/09/27 15:43:39.278899513 Error in rmarkdown::render_site(envir = new.env()) :
2016/09/27 15:43:39.278911296   No site generator found.`

Full Deploy output:
`Preparing to deploy site...DONE
Uploading bundle for site: 1880...DONE
Deploying bundle: 3764 for site: 1880 ...
Bundle requested R version 3.3.0; using /opt/R/3.3.0/bin/R which has version 3.3.0
2016/09/27 15:43:27.792803200 Installed packrat SHA is 5c45d48a3825eb392d618eeb383b0cdcbcccb4a3; packaged packrat SHA is 5c45d48a3825eb392d618eeb383b0cdcbcccb4a3
2016/09/27 15:43:27.794327194 Packrat is up-to-date.
2016/09/27 15:43:27.794505329 R version: 3.3.0
2016/09/27 15:43:27.794574512 packrat version: 0.4.8.1
2016/09/27 15:43:28.100539330 Audited package hashes with local packrat installation.
2016/09/27 15:43:34.391400832 Installing Rcpp (0.12.7) ... 
2016/09/27 15:43:34.427681476 	OK (symlinked cache)
2016/09/27 15:43:34.427946997 Installing assertthat (0.1) ... 
2016/09/27 15:43:34.507151598 	OK (symlinked cache)
2016/09/27 15:43:34.507427834 Installing base64enc (0.1-3) ... 
2016/09/27 15:43:34.589556286 	OK (symlinked cache)
2016/09/27 15:43:34.589838843 Installing bitops (1.0-6) ... 
2016/09/27 15:43:34.613415110 	OK (symlinked cache)
2016/09/27 15:43:34.622455258 Installing digest (0.6.10) ... 
2016/09/27 15:43:34.686528088 	OK (symlinked cache)
2016/09/27 15:43:34.697872350 Installing formatR (1.4) ... 
2016/09/27 15:43:34.776218936 	OK (symlinked cache)
2016/09/27 15:43:34.776506332 Installing highr (0.6) ... 
2016/09/27 15:43:34.826788940 	OK (symlinked cache)
2016/09/27 15:43:34.827059242 Installing jsonlite (1.1) ... 
2016/09/27 15:43:34.874226850 	OK (symlinked cache)
2016/09/27 15:43:34.874493817 Installing lazyeval (0.2.0) ... 
2016/09/27 15:43:34.917585934 	OK (symlinked cache)
2016/09/27 15:43:34.917908131 Installing magrittr (1.5) ... 
2016/09/27 15:43:35.010078622 	OK (symlinked cache)
2016/09/27 15:43:35.010429937 Installing mime (0.5) ... 
2016/09/27 15:43:35.194561462 	OK (symlinked cache)
2016/09/27 15:43:35.194878689 Installing packrat (0.4.8-1) ... 
2016/09/27 15:43:35.287592399 	OK (symlinked cache)
2016/09/27 15:43:35.327171701 Installing stringi (1.1.1) ... 
2016/09/27 15:43:35.445802656 	OK (symlinked cache)
2016/09/27 15:43:35.446101162 Installing yaml (2.1.13) ... 
2016/09/27 15:43:35.505912302 	OK (symlinked cache)
2016/09/27 15:43:35.506615243 Installing caTools (1.17.1) ... 
2016/09/27 15:43:35.523638957 	OK (symlinked cache)
2016/09/27 15:43:35.523914749 Installing htmltools (0.3.5) ... 
2016/09/27 15:43:35.603279402 	OK (symlinked cache)
2016/09/27 15:43:35.603564509 Installing tibble (1.2) ... 
2016/09/27 15:43:35.655131745 	OK (symlinked cache)
2016/09/27 15:43:35.655430276 Installing markdown (0.7.7) ... 
2016/09/27 15:43:35.700333837 	OK (symlinked cache)
2016/09/27 15:43:35.700600765 Installing stringr (1.1.0) ... 
2016/09/27 15:43:35.748936203 	OK (symlinked cache)
2016/09/27 15:43:35.749205395 Installing evaluate (0.9) ... 
2016/09/27 15:43:35.821623524 	OK (symlinked cache)
2016/09/27 15:43:35.822187784 Installing knitr (1.14) ... 
2016/09/27 15:43:35.901384189 	OK (symlinked cache)
2016/09/27 15:43:35.901664844 Installing rmarkdown (1.0.9014) ... 
2016/09/27 15:43:35.968593164 	OK (symlinked cache)
2016/09/27 15:43:35.980654862 Promoting newly installed packages to the package cache.
Completed packrat build against R version: '3.3.0'
Building document...
2016/09/27 15:43:37.959023555 LANG: en_US.UTF-8
2016/09/27 15:43:37.959195382 R version: 3.3.0
2016/09/27 15:43:37.959265787 rmarkdown version: 1.0.9014
2016/09/27 15:43:37.959333710 knitr version: 1.14
2016/09/27 15:43:37.954188793 Using Packrat dir /opt/rstudio-connect/mnt/report/packrat/lib/x86_64-pc-linux-gnu/3.3.0
2016/09/27 15:43:39.278899513 Error in rmarkdown::render_site(envir = new.env()) :
2016/09/27 15:43:39.278911296   No site generator found.
2016/09/27 15:43:39.278923848 Calls: local ... eval.parent -> eval -> eval -> eval -> eval -> <Anonymous>
2016/09/27 15:43:39.279050789 Execution halted
Site deployment failed with error: exit status 1`

**Comment by ajmcoqui** [comment] 2016-09-27 15:52
The problem appears to be with the Publish button in the rendered doc.  If I run these same steps, but use the Publish button in the Code pane of the IDE instead of the Publish button in the rendered doc, the deployment succeeds.

**Comment by ChaitaC** [comment] 2016-09-27 16:30
Still not able to reproduce on previous IDE versions, but I installed **latest preview version of IDE Version 1.0.27 (on desktop)** this morning and able to reproduce it 100%. 

Steps: 

1. Install 1.0.27 on mac
2. Open New Project > New Directory > Empty Project > Populate directory 'Name' > Save  (select 'open new project' or not )
3. File > New file > RMarkdown > Populate 'Title' > Save the file > Click 'Knit'
4. Click 'Publish' button available in the rendered document
![screen shot 2016-09-27 at 11 27 13 am](https://cloud.githubusercontent.com/assets/17551950/18882548/36bf5e62-84a5-11e6-9be0-007d0ba0febc.png)

**Actual result:** Document is considered a site `Preparing to deploy site` and console throws similar error.
 
Note: As @Amanda mentioned, when using publish button in the Code pane of iDE, the document is published successfully.

Seems like something triggers this behavior when you install a new IDE version, may be?

**Comment by jjallaire** [comment] 2016-09-27 16:48
@jmcphers This might be something we need to take for v1.0. 

We haven't yet submitted rsconnect to CRAN but will shortly after we do the blog post.

**Comment by jmcphers** [comment] 2016-09-27 19:27
Yes, we'll take this for 1.0. It turned out to be a typo in the logic that runs specifically when deploying content from a satellite window (which I didn't catch since I didn't run a negative test for deploying website content from satellites). Addressed in RStudio here:

https://github.com/rstudio/rstudio/commit/0b0ff787fda805845e0833a1029da5c77a297fcf

**Closed by jmcphers** 2016-09-27 19:27 UTC
Labels: bug
